name: CI

on:
  push:
    branches:
      - main

jobs:
  Publish-Presentations:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Build all presentations
        run: |
          yarn
          yarn reveal-md "$(pwd)" --static
      - name: Publish
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config user.name "github-actions-bot"
          git config user.email "support+actions@github.com"
          yarn gh-pages -d "$(pwd)/_static" -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
