name: CI

on:
  push:
    # branches:
    #   - main

jobs:
  Build-Presentations:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Build all presentations
        run: |
          for f in $(pwd)/*/package.json; do
            dir="${f%/*}"
            yarn --cwd "$dir" && yarn --cwd "$dir" build
          done
